version: "3.7"

services:
  ui:
    container_name: agr.literature.${REACT_APP_DEV_OR_STAGE_OR_PROD}.ui.server.${COMPOSE_PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${LIT_UI_PORT}:80"
